#! perl

sub on_osc_seq_perl {
	my ($self, $args, $resp) = @_;
	return unless $args =~ s/^im-notify;//;
	my ($visible, $text) = split(';', $args);

	$self->exec_async("canberra-gtk-play", "--id=message-new-instant") unless $self->focus and $visible;
	$self->exec_async("notify-send", "[IM] $text") unless $self->focus;

	()
}
