#! perl

my %last_notified;

sub on_osc_seq_perl {
	my ($self, $args, $resp) = @_;
	return unless $args =~ s/^im-notify;//;
	my ($visible, $tmux_visible, $text) = split(';', $args);

	return unless (time - $last_notified{$text}) > 5;
	$last_notified{$text} = time;

	$self->exec_async('canberra-gtk-play', '--id=message-new-instant') unless $self->focus and $visible and $tmux_visible;
	$self->exec_async('notify-send', '--icon=user-available', '--expire-time=1000', 'Message from', $text) unless $self->focus and $tmux_visible;

	()
}
