#! perl

sub on_osc_seq_perl {
	my ($self, $args, $resp) = @_;
	return unless $args =~ s/^im-notify;//;
	my ($visible, $tmux_visible, $text) = split(';', $args);

	$self->exec_async('canberra-gtk-play', '--id=message-new-instant') unless $self->focus and $visible and $tmux_visible;
	$self->exec_async('notify-send', '--expire-time=1000', 'Message from', $text) unless $self->focus and $tmux_visible;

	()
}
